"""add language to posts

Revision ID: 489f7c052d0d
Revises: f448e62c9d63
Create Date: 2024-04-02 10:09:36.339902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '489f7c052d0d'
down_revision = 'f448e62c9d63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
